### ISSUE TITLE
Add option to remove Jetpack Related Posts

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/newspack-listings#115]
Both Local Profile and Gay Desert Guide have asked us to remove Jetpack's related posts from their listings. In light of the fact that listings are often in competition with each other, it would make sense for us to include a means to easily toggle those off. 

For now, we've added some CSS to accommodate:

```
/* Hide Jetpack Related Posts from Listings CPTs */

.newspack_lst_generic-template .newspack_lst_place-template .newspack_lst_mktplce-template .jp-relatedposts, [class^="jp-relatedposts"] {
	display: none !important;
}
```

**Comment by dkoo** [comment]
Noting for future reference that the above CSS is incorrect (it ends up hiding the Related Posts module everywhere instead of just on singular listings). The correct CSS is:

```
.newspack_lst_event-template [class^="jp-relatedposts"],
.newspack_lst_generic-template [class^="jp-relatedposts"],
.newspack_lst_mktplce-template [class^="jp-relatedposts"],
.newspack_lst_place-template [class^="jp-relatedposts"] {
	display: none !important;
}
```
