### ISSUE TITLE
Fix "Hide Related Listings" toggle

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/newspack-listings#236]
The toggle to **Hide Related Listings** in the post sidebar doesn't persist on save or publish. To replicate:

1. On a site with Listings set up, create a new post. 
2. In the "Related Newspack Listings" section, click to activate "Hide Related Listings"
3. Save.
4. Note that the toggle automatically reverts to the off position.

**Comment by adekbadek** [comment]
Closing, this will be obviated by https://github.com/Automattic/newspack-listings/pull/256
