### ISSUE TITLE
Curated List Block: Reusable Block no longer loads styles

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-listings#291]
When you make the Curated List block resuable, the block styles are no longer loaded on the page. 

I think it has to do with the check [here](https://github.com/Automattic/newspack-listings/blob/25f4be8dd216b00ee73cc952dd2e9f93728def03/includes/class-blocks.php#L211-L219) that's looking for a Curated List block in the content before enqueuing the styles, but I'm not 100% sure. 

## Steps to reproduce

1. Add a Curated List block to the content
2. Change some of the styles -- for example, shrink the font size and align images to the left.
3. Publish and view on the front end: 

![image](https://user-images.githubusercontent.com/177561/182700183-d8fb35d1-3ea5-4138-afee-e3815ab328ec.png)

4. Edit the page again and make the block reusable; republish. 
5. View on the front-end again; note the styles from the block are no longer applied:

![image](https://user-images.githubusercontent.com/177561/182700938-681fdb98-5c39-4422-b129-2233d3bedec2.png)

**Comment by laurelfulford** [comment]
It looks like the same kind of issue is happening when the block is placed in a widget area when it's the only one on the page: 

![image](https://user-images.githubusercontent.com/177561/182930872-7d8cb2e1-9fff-42ec-83e9-930cbd94b089.png)

**Comment by mjonasftc** [comment]
It's happening when this block is placed in a widget area even when there are other widget blocks present in that area.

**Comment by mjonasftc** [comment]
It also appears that these blocks will not take any custom CSS using a custom class if it's being used in the Widget area
<img width="1137" alt="eeoug1l6qzy0oh-additional css class not output" src="https://user-images.githubusercontent.com/74475331/184682359-9388ab6b-5706-41df-8b07-20299de80a20.png">

**Comment by laurelfulford** [comment]
> It also appears that these blocks will not take any custom CSS using a custom class if it's being used in the Widget area

This also happens with the block when added to the regular content -- there's a separate bug for that one [here](https://github.com/Automattic/newspack-listings/issues/278)!
