### ISSUE TITLE
Settings: Listings permalink prefix for Events, Generic Listings, Marketplace Items, Places

### ISSUE THREAD

**Issue by schwabing** [Automattic/newspack-listings#41]
Today, I can edit /listings in settings, but items, marketplace and places are fixed:
- /listings/items/
- /listings/marketplace/
- /listings/places/

For an even more generic use (our case: product/service listings, people directory), I'd like to be able to modify permalink prefixes for each listing type:
- /directory/people/ (generic)
- /directory/products/ (marketplace)
- /directory/bikeshops/ (places)

**Comment by dkoo** [comment]
This is a good suggestion, thanks for filing!
